# Generated by Django 3.2.5 on 2021-07-28 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210728_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='variant_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
