# Generated by Django 3.2.5 on 2021-07-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_answer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='variant_id',
            new_name='variants_numbers',
        ),
    ]
